name: project_popcon_flutter
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  persistent_bottom_nav_bar: ^6.2.1
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  carousel_slider: ^5.0.0
  http: ^1.2.2
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    # - images/logo.jpeg

  # fonts:
  # - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
